name: lost_things
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  easy_localization: ^1.3.5
  font_awesome_flutter: ^8.5.0
  carousel_slider: ^1.4.1
  image_picker: ^0.6.3+1
  dotted_border: ^1.0.4
  auto_animated: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/my_images/
   - assets/languages/
   - assets/fonts/

  fonts:
    - family: MainFont
      fonts:
        - asset: assets/fonts/JF-Flat-regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
